Repository cloudquery/helm-charts, pull requests merged in 2022-03, with the labels that each got.

#10 fix: Fix broken log commandline
  templates/NOTES.txt
Labels: fix

#11 feat: Add note about installing psql in the admin container
  templates/NOTES.txt
Labels: feat

#8 chore: Synced file(s) with cloudquery/.github
  .github/workflows/README
  CODEOWNERS
Labels: ignore-for-release

#13 chore: Sync form .github
  .github/workflows/issue_to_project.yml
Labels: ignore-for-release
